FROM python:3.9-slim

# set the working directory

WORKDIR /app


#Copy the current directory contents into the container at /app
COPY . /app

#install any needed package specified in the reuqiremnts.txt
RUN pip install flask, pytest

#make port 5000 avaible to the world outside this container
EXPOSE 5000

#run app.py when the container launches

CMD ['python', 'app.py']