name: CI/CD for Dockerized Flask app

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # step 1: check out the code from repository
    - name: check out code   
      uses: actions/checkout@v4

    # step 2 : Setup Python Environmnet   
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    
    #step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # step 4: Run tests
    - name: Test with pytest
      run: |
        pytest
      
  build-and-test:
    needs: build-and-test
    runs-on: ubunut-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: check out Docker build   
      uses: docker/setup-buildx-actions@v2

    - name: login Dockerhub   
      uses: docker/login-actions@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    -name: Build and push Docker image
     uses: docker/build-push-actions@v4
     with:
        context:
        push: true:
        tages: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
